'use client'

import { yupResolver } from '@hookform/resolvers/yup'
import { useEffect } from 'react'
import { Button, Card, CardBody, CardHeader, CardTitle, Col, Form, Row } from 'react-bootstrap'
import { Controller, useForm } from 'react-hook-form'
import { useRouter } from 'next/navigation'
import * as yup from 'yup'
import PageTitle from '@/components/PageTitle'
import TextAreaFormInput from '@/components/from/TextAreaFormInput'
import TextFormInput from '@/components/from/TextFormInput'
import { useGetAgencyDirectory, useUpdateAgencyDirectory } from '@/hooks/useAgencyDirectory'

type Values = { agency_name: string; email: string; phone: string; website?: string; description?: string; address: string; city: string; state: string; country: string; postal_code: string; contact_person_name: string; contact_person_email: string; contact_person_phone: string; agency_type: 'RESIDENTIAL' | 'COMMERCIAL' | 'MIXED'; employee_count?: number; is_active: boolean }
const schema = yup.object({ agency_name: yup.string().trim().required(), email: yup.string().trim().email().required(), phone: yup.string().trim().required(), website: yup.string().transform((value, original) => original === '' ? undefined : value).url().optional(), description: yup.string().optional(), address: yup.string().trim().required(), city: yup.string().trim().required(), state: yup.string().trim().required(), country: yup.string().trim().required(), postal_code: yup.string().trim().required(), contact_person_name: yup.string().trim().required(), contact_person_email: yup.string().trim().email().required(), contact_person_phone: yup.string().trim().required(), agency_type: yup.string().oneOf(['RESIDENTIAL', 'COMMERCIAL', 'MIXED']).required(), employee_count: yup.number().transform((v, original) => original === '' ? undefined : v).positive().optional(), is_active: yup.boolean().required() })

const AgencyEdit = ({ agencyId }: { agencyId: string }) => {
  const router = useRouter(); const agencyQuery = useGetAgencyDirectory(agencyId); const updateAgency = useUpdateAgencyDirectory();
  const { control, handleSubmit, reset } = useForm<Values>({ resolver: yupResolver(schema) as any });
  useEffect(() => { if (!agencyQuery.data) return; const a = agencyQuery.data; reset({ agency_name: a.name || '', email: a.email || '', phone: a.phone || '', website: a.website || '', description: a.description || '', address: a.address || '', city: a.city || '', state: a.state || '', country: a.country || '', postal_code: a.postal_code || '', contact_person_name: a.contact_person_name || '', contact_person_email: a.contact_person_email || '', contact_person_phone: a.contact_person_phone || '', agency_type: ((a.agency_type || 'RESIDENTIAL').toUpperCase() as Values['agency_type']), employee_count: a.employee_count || undefined, is_active: a.is_active !== false }); }, [agencyQuery.data, reset]);
  const submit = async (values: Values) => { await updateAgency.mutateAsync({ agencyId, payload: values }); router.push(`/agencies/${agencyId}`); };
  if (agencyQuery.isLoading) return <div className="text-center py-5">Loading agency...</div>;
  if (agencyQuery.error || !agencyQuery.data) return <Card><CardBody className="text-center py-5 text-danger">{agencyQuery.error instanceof Error ? agencyQuery.error.message : 'Agency not found'}</CardBody></Card>;
  return <><PageTitle title="Edit Agency" subName="People" /><form onSubmit={handleSubmit(submit)}><Card><CardHeader><CardTitle as="h4">Agency identity and contact details</CardTitle></CardHeader><CardBody><Row className="g-3"><Col lg={6}><TextFormInput control={control} name="agency_name" label="Agency Name" /></Col><Col lg={6}><TextFormInput control={control} name="email" type="email" label="Agency Email" /></Col><Col lg={6}><TextFormInput control={control} name="phone" label="Phone" /></Col><Col lg={6}><TextFormInput control={control} name="website" label="Website" /></Col><Col lg={12}><TextAreaFormInput control={control} name="description" label="Description" rows={3} /></Col><Col lg={12}><TextFormInput control={control} name="address" label="Address" /></Col><Col lg={6}><TextFormInput control={control} name="city" label="City" /></Col><Col lg={6}><TextFormInput control={control} name="state" label="State" /></Col><Col lg={6}><TextFormInput control={control} name="country" label="Country" /></Col><Col lg={6}><TextFormInput control={control} name="postal_code" label="Postal Code" /></Col><Col lg={4}><TextFormInput control={control} name="contact_person_name" label="Primary Contact" /></Col><Col lg={4}><TextFormInput control={control} name="contact_person_email" type="email" label="Contact Email" /></Col><Col lg={4}><TextFormInput control={control} name="contact_person_phone" label="Contact Phone" /></Col><Col lg={6}><Form.Label>Agency Type</Form.Label><Controller name="agency_type" control={control} render={({ field }) => <Form.Select {...field}><option value="RESIDENTIAL">Residential</option><option value="COMMERCIAL">Commercial</option><option value="MIXED">Mixed</option></Form.Select>} /></Col><Col lg={6}><TextFormInput control={control} name="employee_count" type="number" label="Employee Count" /></Col><Col lg={12}><Controller name="is_active" control={control} render={({ field }) => <Form.Check type="switch" id="agency-edit-active" label="Agency is active" checked={field.value} onChange={(event) => field.onChange(event.target.checked)} />} /></Col></Row></CardBody></Card><div className="text-end mt-3"><Button type="button" variant="outline-secondary" className="me-2" onClick={() => router.push(`/agencies/${agencyId}`)}>Cancel</Button><Button type="submit" disabled={updateAgency.isPending}>{updateAgency.isPending ? 'Saving...' : 'Save Agency'}</Button></div></form></>;
}
export default AgencyEdit
