import { z } from 'zod';

const nonEmptyString = z.string().min(1);
const email = z.string().email();

const booleanFromString = z.preprocess((value) => {
  if (value === 'true' || value === true) return true;
  if (value === 'false' || value === false) return false;
  return value;
}, z.boolean());

const optionalString = nonEmptyString.optional();
const nonEmptyObject = z
  .object({})
  .passthrough()
  .refine((value) => Object.keys(value).length > 0, { message: 'Request body cannot be empty' });

const allowedRoles = z.enum([
  'user',
  'guard',
  'admin',
  'superadmin',
  'agency_manager',
  'facility_manager',
]);

const onboardingRoles = z.enum(['agency_manager', 'facility_manager']);
const onboardingStatuses = z.enum(['pending', 'approved', 'rejected']);

const pageLimitQuery = z.object({
  page: z.coerce.number().int().min(1).optional(),
  limit: z.coerce.number().int().min(1).max(200).optional(),
});

const offsetQuery = z.object({
  offset: z.coerce.number().int().min(0).optional(),
});

const withSearchQuery = z.object({
  search: optionalString,
});

const idParam = z.object({ id: nonEmptyString });
const uuidParam = z.object({ id: z.string().uuid() });
const paymentChargeScope = z.enum(['agency', 'community']);
const paymentChargeType = z.enum(['fixed', 'variable', 'formula']);
const paymentChargeFrequency = z.enum(['monthly', 'quarterly', 'yearly', 'one_time', 'custom_period']);
const paymentChargeLateFeeType = z.enum(['none', 'fixed', 'percentage']);
const paymentChargeTargetType = z.enum([
  'all_units',
  'unit_ids',
  'blocks',
  'unit_types',
  'occupied_only',
  'owner_only',
  'tenant_only',
  'exclude_unit_ids',
]);
const paymentChargeRunStatus = z.enum(['draft', 'previewed', 'issued', 'cancelled']);
const payoutDestinationType = z.enum(['bank_account', 'mobile_money']);
const payoutRequestAction = z.enum(['cancel', 'approve', 'reject', 'mark_processing', 'mark_paid', 'fail']);
const payoutRuleShareMode = z.enum(['fixed', 'percentage']);
const payoutRuleAgencyShareMode = z.enum(['remainder', 'fixed', 'percentage']);
const adminEmailFolder = z.enum(['all', 'inbox', 'sent', 'drafts', 'draft', 'archive', 'archived', 'deleted', 'trash', 'starred', 'important']);
const adminEmailPriority = z.enum(['low', 'normal', 'high', 'urgent']);
const adminEmailAction = z.enum(['draft', 'queue']);
const adminEmailStatus = z.enum(['draft', 'queued', 'processing', 'sent', 'delivered', 'failed']);
const paymentChargeTemplateTargetSchema = z.object({
  target_type: paymentChargeTargetType,
  target_value: z.union([z.string(), z.array(z.string()), z.record(z.any())]).optional(),
});

const atLeastOne = <T extends z.ZodTypeAny>(schema: T) =>
  schema.refine((value) => Object.keys(value as Record<string, unknown>).length > 0, {
    message: 'At least one field is required',
  });

export const schemas = {
  idParam,
  authRegister: z.object({
    email,
    password: nonEmptyString,
    firstName: nonEmptyString,
    lastName: nonEmptyString,
  }),
  authLogin: z.object({
    email,
    password: nonEmptyString,
  }),
  accountDelete: z.object({
    current_password: nonEmptyString,
    confirmation_text: nonEmptyString,
    reason: optionalString,
    reason_details: z.string().max(1000).optional(),
  }),
  accountDeactivate: z.object({
    reason: optionalString,
    reason_details: z.string().max(1000).optional(),
  }),
  accountBackupRestore: z.object({
    source_path: optionalString,
  }),
  accountBackupCleanup: z.object({
    retention_days: z.coerce.number().int().min(1).max(365).optional(),
  }),
  accountAppUpdateStatusQuery: z.object({
    platform: z.enum(['ios', 'android', 'web']).optional(),
    channel: z.enum(['stable', 'beta']).optional(),
    current_version: optionalString,
    current_build: optionalString,
  }),

  onboardingCreate: z.object({
    requested_role: onboardingRoles,
    first_name: nonEmptyString,
    last_name: nonEmptyString,
    email,
    phone: optionalString,
    organization_name: optionalString,
    community_name: optionalString,
    country: optionalString,
    city: optionalString,
    address: optionalString,
    referral_code: optionalString,
    source: optionalString,
    metadata: z.record(z.any()).optional().nullable(),
  }),
  onboardingListQuery: pageLimitQuery
    .merge(offsetQuery)
    .merge(withSearchQuery)
    .extend({
      status: onboardingStatuses.optional(),
      requested_role: onboardingRoles.optional(),
    }),
  onboardingUpdateParams: uuidParam,
  onboardingUpdateBody: atLeastOne(
    z.object({
      status: onboardingStatuses.optional(),
      review_notes: z.string().optional().nullable(),
      invited_user_id: z.string().uuid().optional().nullable(),
    })
  ),

  adminAnalyticsQuery: z.object({
    timeFrame: optionalString,
  }),
  adminUsersListQuery: pageLimitQuery.merge(withSearchQuery).extend({
    role: allowedRoles.optional(),
  }),
  adminCreateUser: z.object({
    email,
    password: nonEmptyString,
    first_name: optionalString,
    last_name: optionalString,
    role: allowedRoles.optional(),
    phone: optionalString,
  }),
  adminInviteUser: z.object({
    email,
    first_name: optionalString,
    last_name: optionalString,
    role: allowedRoles.optional(),
    phone: optionalString,
  }),
  adminUpdateUserParams: idParam,
  adminUpdateUserBody: atLeastOne(
    z.object({
      first_name: optionalString,
      last_name: optionalString,
      role: allowedRoles.optional(),
      phone: optionalString,
      profile_pic_url: optionalString,
      is_active: z.boolean().optional(),
    })
  ),
  adminBulkUpdateUsers: z.object({
    userIds: z.array(nonEmptyString).nonempty(),
    updates: nonEmptyObject,
  }).superRefine((value, ctx) => {
    if ('role' in value.updates && value.updates.role !== undefined) {
      const result = allowedRoles.safeParse(value.updates.role);
      if (!result.success) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['updates', 'role'],
          message: 'Invalid role provided',
        });
      }
    }
  }),

  adminCommunityCreate: nonEmptyObject,
  adminCommunityUpdate: nonEmptyObject,
  adminUnitCreate: nonEmptyObject,
  adminUnitUpdate: nonEmptyObject,
  adminProfileCreate: nonEmptyObject.superRefine((value, ctx) => {
    if ('role' in value && value.role !== undefined) {
      const result = allowedRoles.safeParse(value.role);
      if (!result.success) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['role'],
          message: 'Invalid role provided',
        });
      }
    }
  }),
  adminProfileUpdate: nonEmptyObject.superRefine((value, ctx) => {
    if ('role' in value && value.role !== undefined) {
      const result = allowedRoles.safeParse(value.role);
      if (!result.success) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['role'],
          message: 'Invalid role provided',
        });
      }
    }
  }),
  adminMessageCreate: nonEmptyObject,
  adminMessageUpdate: nonEmptyObject,

  adminNotificationCreate: z
    .object({
      title: optionalString,
      name: optionalString,
      type: nonEmptyString,
      recipients_count: z.number().int().min(0).optional(),
      message: z.string().optional(),
      template: z.string().optional(),
      template_id: z.coerce.number().int().positive().optional().nullable(),
      audience: z.any().optional(),
      budget: z.number().optional().nullable(),
      spent: z.number().optional().nullable(),
      scheduled_at: z.string().optional().nullable(),
      sent_at: z.string().optional().nullable(),
      status: z.enum(['draft', 'scheduled', 'active', 'completed', 'paused', 'processing', 'delivered', 'failed']).optional(),
    })
    .refine((value) => value.name || value.title, {
      message: 'name or title is required',
      path: ['name'],
    }),
  adminNotificationUpdate: atLeastOne(
    z
      .object({
        title: optionalString,
        name: optionalString,
        message: z.string().optional(),
        template: z.string().optional(),
        template_id: z.coerce.number().int().positive().optional().nullable(),
        status: z.enum(['draft', 'scheduled', 'active', 'completed', 'paused', 'processing', 'delivered', 'failed']).optional(),
      })
      .passthrough()
  ),
  adminNotificationTemplateCreate: z.object({
    name: nonEmptyString,
    template_name: optionalString,
    type: nonEmptyString,
    category: optionalString,
    subject: optionalString.nullable(),
    content: nonEmptyString,
    template_content: optionalString,
    variables: z.array(z.string()).optional(),
    status: z.enum(['active', 'draft', 'archived']).optional(),
  }),
  adminNotificationTemplateUpdate: atLeastOne(
    z.object({
      name: optionalString,
      template_name: optionalString,
      type: optionalString,
      category: optionalString,
      subject: optionalString.nullable(),
      content: optionalString,
      template_content: optionalString,
      variables: z.array(z.string()).optional(),
      status: z.enum(['active', 'draft', 'archived']).optional(),
    })
  ),
  adminEmailsListQuery: pageLimitQuery.extend({
    folder: adminEmailFolder.optional(),
    status: adminEmailStatus.optional(),
    priority: adminEmailPriority.optional(),
    search: optionalString,
  }),
  adminEmailsContactsQuery: z.object({
    search: optionalString,
  }),
  adminEmailCreate: z.object({
    recipient_id: nonEmptyString,
    subject: nonEmptyString,
    body: nonEmptyString,
    priority: adminEmailPriority.optional(),
    action: adminEmailAction.optional(),
  }),
  adminEmailUpdate: atLeastOne(
    z.object({
      is_read: booleanFromString.optional(),
      is_starred: booleanFromString.optional(),
      is_important: booleanFromString.optional(),
      folder: adminEmailFolder.exclude(['all']).optional(),
      status: adminEmailStatus.optional(),
      subject: optionalString,
      body: optionalString,
      priority: adminEmailPriority.optional(),
    })
  ),

  adminSocietyCreate: z.object({
    name: nonEmptyString,
    address: optionalString,
    description: optionalString,
  }),
  adminSocietyUpdate: atLeastOne(
    z.object({
      name: optionalString,
      address: optionalString,
      description: optionalString,
    })
  ),

  adminBulkUpdateMaintenance: z.object({
    requestIds: z.array(nonEmptyString).nonempty(),
    updates: nonEmptyObject,
  }),
  adminBulkUpdateComplaints: z.object({
    complaintIds: z.array(nonEmptyString).nonempty(),
    updates: nonEmptyObject,
  }),
  adminBulkUpdatePayments: z.object({
    paymentIds: z.array(nonEmptyString).nonempty(),
    updates: nonEmptyObject,
  }),
  adminGeneratePayments: z.object({
    societyId: nonEmptyString,
    unitIds: z.array(nonEmptyString).optional(),
    amount: z.coerce.number(),
    dueDate: nonEmptyString,
    description: z.string().optional(),
  }),
  adminBulkCreateNotices: z.object({
    notices: z.array(nonEmptyObject).nonempty(),
  }),
  adminSettingsUpdate: nonEmptyObject,
  adminDeleteSettingParams: z.object({ key: nonEmptyString }),
  adminConfigurationIdParam: z.object({ id: z.string().uuid() }),
  adminCommunityConfigurationsQuery: z.object({
    community_id: z.string().uuid().optional(),
  }),
  adminCommunityConfigurationUpdate: nonEmptyObject,
  adminAgencyConfigurationsQuery: z.object({
    agency_id: z.string().uuid().optional(),
  }),
  adminAgencyConfigurationCreate: z
    .object({
      agency_id: z.string().uuid(),
      agency_name: nonEmptyString,
    })
    .passthrough(),
  adminAgencyConfigurationUpdate: nonEmptyObject,
  adminGuardOperationsQuery: z.object({
    community_id: z.string().uuid().optional(),
    guard_id: z.string().uuid().optional(),
    search: optionalString,
  }),
  adminGuardProfileCreate: z.object({
    first_name: nonEmptyString,
    last_name: nonEmptyString,
    email,
    phone: z.string().optional().nullable(),
    guard_phone: z.string().optional().nullable(),
    date_of_birth: z.string().optional().nullable(),
    address: z.string().optional().nullable(),
    community_id: z.string().uuid(),
    shift_type: z.enum(['morning', 'evening', 'night', 'rotating']).optional(),
    shift_start_time: z.string().optional().nullable(),
    shift_end_time: z.string().optional().nullable(),
    gate_assignment: z.string().optional().nullable(),
    license_number: z.string().optional().nullable(),
    employment_date: z.string().optional().nullable(),
    salary: z.coerce.number().positive().optional().nullable(),
    emergency_contact_name: z.string().optional().nullable(),
    emergency_contact_phone: z.string().optional().nullable(),
    assignment_name: z.string().optional().nullable(),
    special_instructions: z.string().optional().nullable(),
    status: z.enum(['active', 'inactive', 'suspended']).optional(),
  }),
  adminGuardScheduleCreate: z.object({
    guard_id: z.string().uuid(),
    shift_type: nonEmptyString,
    start_time: nonEmptyString,
    end_time: nonEmptyString,
    assigned_date: nonEmptyString,
    end_date: z.string().optional().nullable(),
    community_id: z.string().uuid().optional().nullable(),
    post_location: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    notes: z.string().optional().nullable(),
    replacement_id: z.string().uuid().optional().nullable(),
  }),
  adminGuardScheduleUpdate: atLeastOne(
    z.object({
      guard_id: z.string().uuid().optional(),
      shift_type: nonEmptyString.optional(),
      start_time: nonEmptyString.optional(),
      end_time: nonEmptyString.optional(),
      assigned_date: nonEmptyString.optional(),
      end_date: z.string().optional().nullable(),
      community_id: z.string().uuid().optional().nullable(),
      post_location: z.string().optional().nullable(),
      status: z.string().optional().nullable(),
      notes: z.string().optional().nullable(),
      replacement_id: z.string().uuid().optional().nullable(),
    })
  ),
  adminGuardAssignmentCreate: z.object({
    community_id: z.string().uuid(),
    guard_id: z.string().uuid(),
    shift_type: nonEmptyString,
    start_time: nonEmptyString,
    end_time: nonEmptyString,
    days_of_week: z.array(z.coerce.number().int().min(0).max(6)).nonempty(),
    start_date: nonEmptyString,
    end_date: z.string().optional().nullable(),
    assignment_name: z.string().optional().nullable(),
    assigned_gate: z.string().optional().nullable(),
    assigned_location: z.string().optional().nullable(),
    patrol_areas: z.array(z.string()).optional(),
    responsibilities: z.array(z.string()).optional(),
    special_instructions: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    current_status: z.string().optional().nullable(),
    is_permanent: z.boolean().optional(),
    is_temporary: z.boolean().optional(),
    backup_guard_id: z.string().uuid().optional().nullable(),
    supervisor_id: z.string().uuid().optional().nullable(),
  }),
  adminGuardAssignmentUpdate: atLeastOne(
    z.object({
      community_id: z.string().uuid().optional(),
      guard_id: z.string().uuid().optional(),
      shift_type: nonEmptyString.optional(),
      start_time: nonEmptyString.optional(),
      end_time: nonEmptyString.optional(),
      days_of_week: z.array(z.coerce.number().int().min(0).max(6)).optional(),
      start_date: nonEmptyString.optional(),
      end_date: z.string().optional().nullable(),
      assignment_name: z.string().optional().nullable(),
      assigned_gate: z.string().optional().nullable(),
      assigned_location: z.string().optional().nullable(),
      patrol_areas: z.array(z.string()).optional(),
      responsibilities: z.array(z.string()).optional(),
      special_instructions: z.string().optional().nullable(),
      status: z.string().optional().nullable(),
      current_status: z.string().optional().nullable(),
      is_permanent: z.boolean().optional(),
      is_temporary: z.boolean().optional(),
      backup_guard_id: z.string().uuid().optional().nullable(),
      supervisor_id: z.string().uuid().optional().nullable(),
    })
  ),
  adminGuardEquipmentCreate: z.object({
    name: nonEmptyString,
    serial_number: z.string().optional().nullable(),
    category: z.string().optional().nullable(),
    type: z.string().optional().nullable(),
    brand: z.string().optional().nullable(),
    model: z.string().optional().nullable(),
    purchase_date: z.string().optional().nullable(),
    warranty_expiry: z.string().optional().nullable(),
    condition: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    location: z.string().optional().nullable(),
    cost: z.coerce.number().optional(),
    assigned_to: z.string().uuid().optional().nullable(),
    last_maintenance: z.string().optional().nullable(),
    next_maintenance: z.string().optional().nullable(),
    notes: z.string().optional().nullable(),
    equipment_type: z.string().optional().nullable(),
    assignment_date: z.string().optional().nullable(),
    last_maintenance_date: z.string().optional().nullable(),
  }),
  adminGuardEquipmentUpdate: atLeastOne(
    z.object({
      name: nonEmptyString.optional(),
      serial_number: z.string().optional().nullable(),
      category: z.string().optional().nullable(),
      type: z.string().optional().nullable(),
      brand: z.string().optional().nullable(),
      model: z.string().optional().nullable(),
      purchase_date: z.string().optional().nullable(),
      warranty_expiry: z.string().optional().nullable(),
      condition: z.string().optional().nullable(),
      status: z.string().optional().nullable(),
      location: z.string().optional().nullable(),
      cost: z.coerce.number().optional(),
      assigned_to: z.string().uuid().optional().nullable(),
      last_maintenance: z.string().optional().nullable(),
      next_maintenance: z.string().optional().nullable(),
      notes: z.string().optional().nullable(),
      equipment_type: z.string().optional().nullable(),
      assignment_date: z.string().optional().nullable(),
      last_maintenance_date: z.string().optional().nullable(),
    })
  ),
  adminGuardPerformanceCreate: z.object({
    guard_id: z.string().uuid(),
    evaluation_period: z.string().optional().nullable(),
    evaluation_date: nonEmptyString,
    evaluator: z.string().optional().nullable(),
    attendance_score: z.coerce.number().optional(),
    punctuality_score: z.coerce.number().optional(),
    discipline_score: z.coerce.number().optional(),
    vigilance_score: z.coerce.number().optional(),
    communication_score: z.coerce.number().optional(),
    overall_score: z.coerce.number().optional(),
    feedback: z.string().optional().nullable(),
    areas_of_improvement: z.string().optional().nullable(),
    commendations: z.string().optional().nullable(),
    training_recommendations: z.record(z.any()).optional(),
    appearance_score: z.coerce.number().optional(),
    knowledge_score: z.coerce.number().optional(),
    reliability_score: z.coerce.number().optional(),
    professionalism_score: z.coerce.number().optional(),
    comments: z.string().optional().nullable(),
    improvement_plan: z.string().optional().nullable(),
    follow_up_date: z.string().optional().nullable(),
    reviewed_by: z.string().optional().nullable(),
  }),
  adminGuardPerformanceUpdate: atLeastOne(
    z.object({
      guard_id: z.string().uuid().optional(),
      evaluation_period: z.string().optional().nullable(),
      evaluation_date: nonEmptyString.optional(),
      evaluator: z.string().optional().nullable(),
      attendance_score: z.coerce.number().optional(),
      punctuality_score: z.coerce.number().optional(),
      discipline_score: z.coerce.number().optional(),
      vigilance_score: z.coerce.number().optional(),
      communication_score: z.coerce.number().optional(),
      overall_score: z.coerce.number().optional(),
      feedback: z.string().optional().nullable(),
      areas_of_improvement: z.string().optional().nullable(),
      commendations: z.string().optional().nullable(),
      training_recommendations: z.record(z.any()).optional(),
      appearance_score: z.coerce.number().optional(),
      knowledge_score: z.coerce.number().optional(),
      reliability_score: z.coerce.number().optional(),
      professionalism_score: z.coerce.number().optional(),
      comments: z.string().optional().nullable(),
      improvement_plan: z.string().optional().nullable(),
      follow_up_date: z.string().optional().nullable(),
      reviewed_by: z.string().optional().nullable(),
    })
  ),
  adminGuardTrainingCreate: z.object({
    guard_id: z.string().uuid(),
    training_name: nonEmptyString,
    description: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    start_date: z.string().optional().nullable(),
    end_date: z.string().optional().nullable(),
    certification: z.string().optional().nullable(),
    certification_expiry: z.string().optional().nullable(),
    conducted_by: z.string().optional().nullable(),
    score: z.coerce.number().optional(),
    notes: z.string().optional().nullable(),
    training_type: z.string().optional().nullable(),
    completion_date: z.string().optional().nullable(),
    expiry_date: z.string().optional().nullable(),
    certification_number: z.string().optional().nullable(),
    trainer: z.string().optional().nullable(),
    location: z.string().optional().nullable(),
  }),
  adminGuardTrainingUpdate: atLeastOne(
    z.object({
      guard_id: z.string().uuid().optional(),
      training_name: nonEmptyString.optional(),
      description: z.string().optional().nullable(),
      status: z.string().optional().nullable(),
      start_date: z.string().optional().nullable(),
      end_date: z.string().optional().nullable(),
      certification: z.string().optional().nullable(),
      certification_expiry: z.string().optional().nullable(),
      conducted_by: z.string().optional().nullable(),
      score: z.coerce.number().optional(),
      notes: z.string().optional().nullable(),
      training_type: z.string().optional().nullable(),
      completion_date: z.string().optional().nullable(),
      expiry_date: z.string().optional().nullable(),
      certification_number: z.string().optional().nullable(),
      trainer: z.string().optional().nullable(),
      location: z.string().optional().nullable(),
    })
  ),
  adminAgencyOperationsQuery: z.object({
    agency_id: z.string().uuid().optional(),
    search: optionalString,
  }),
  adminAgencyDirectoryCreate: z.object({
    agency_name: nonEmptyString,
    email,
    phone: nonEmptyString,
    website: z.string().url().optional().nullable(),
    description: z.string().optional().nullable(),
    address: nonEmptyString,
    city: nonEmptyString,
    state: nonEmptyString,
    country: nonEmptyString,
    postal_code: nonEmptyString,
    contact_person_name: nonEmptyString,
    contact_person_email: email,
    contact_person_phone: nonEmptyString,
    contact_person_position: z.string().optional().nullable(),
    establishment_date: nonEmptyString,
    agency_type: z.enum(['RESIDENTIAL', 'COMMERCIAL', 'MIXED']),
    facebook_url: z.string().url().optional().nullable(),
    instagram_url: z.string().url().optional().nullable(),
    twitter_url: z.string().url().optional().nullable(),
    linkedin_url: z.string().url().optional().nullable(),
    operating_hours: z.string().optional().nullable(),
    languages_spoken: z.array(z.string()).optional(),
    specializations: z.array(z.string()).optional(),
    certifications: z.array(z.string()).optional(),
    employee_count: z.coerce.number().int().min(1).optional().nullable(),
    is_active: z.boolean().optional(),
    notification_preferences: z.array(z.string()).optional(),
    managed_communities: z.array(
      z.object({
        community_name: nonEmptyString,
        address: nonEmptyString,
        city: nonEmptyString,
        state: nonEmptyString,
        country: nonEmptyString,
        description: z.string().optional().nullable(),
        established_date: z.string().optional().nullable(),
      })
    ).min(1),
  }),
  adminAgencyProfileCreate: z.object({
    id: z.string().uuid(),
    name: nonEmptyString,
    address: nonEmptyString,
    city: nonEmptyString,
    state: nonEmptyString,
    pincode: nonEmptyString,
    agency_type: z.string().optional().nullable(),
    category: z.string().optional().nullable(),
    owner_name: z.string().optional().nullable(),
    manager_name: z.string().optional().nullable(),
    license_number: z.string().optional().nullable(),
    website: z.string().url().optional().nullable(),
    description: z.string().optional().nullable(),
    email: email.optional().nullable(),
    phone: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    established_year: z.union([z.string(), z.number()]).optional().nullable(),
    commission_rate: z.coerce.number().optional().nullable(),
    total_agents: z.coerce.number().optional().nullable(),
    total_clients: z.coerce.number().optional().nullable(),
    total_properties: z.coerce.number().optional().nullable(),
    average_deal_value: z.coerce.number().optional().nullable(),
    account_holder_name: z.string().optional().nullable(),
    account_number: z.string().optional().nullable(),
    bank_name: z.string().optional().nullable(),
    ifsc_code: z.string().optional().nullable(),
    specializations: z.array(z.string()).optional(),
    services: z.array(z.string()).optional(),
    contact_persons: z.array(z.any()).optional().nullable(),
    documents: z.array(z.any()).optional().nullable(),
  }),
  adminAgencyProfileUpdate: atLeastOne(
    z.object({
      name: nonEmptyString.optional(),
      address: nonEmptyString.optional(),
      city: nonEmptyString.optional(),
      state: nonEmptyString.optional(),
      pincode: nonEmptyString.optional(),
      agency_type: z.string().optional().nullable(),
      category: z.string().optional().nullable(),
      owner_name: z.string().optional().nullable(),
      manager_name: z.string().optional().nullable(),
      license_number: z.string().optional().nullable(),
      website: z.string().url().optional().nullable(),
      description: z.string().optional().nullable(),
      email: email.optional().nullable(),
      phone: z.string().optional().nullable(),
      status: z.string().optional().nullable(),
      established_year: z.union([z.string(), z.number()]).optional().nullable(),
      commission_rate: z.coerce.number().optional().nullable(),
      total_agents: z.coerce.number().optional().nullable(),
      total_clients: z.coerce.number().optional().nullable(),
      total_properties: z.coerce.number().optional().nullable(),
      average_deal_value: z.coerce.number().optional().nullable(),
      account_holder_name: z.string().optional().nullable(),
      account_number: z.string().optional().nullable(),
      bank_name: z.string().optional().nullable(),
      ifsc_code: z.string().optional().nullable(),
      specializations: z.array(z.string()).optional(),
      services: z.array(z.string()).optional(),
      contact_persons: z.array(z.any()).optional().nullable(),
      documents: z.array(z.any()).optional().nullable(),
    })
  ),
  adminAgencyStaffCreate: z.object({
    agency_id: z.string().uuid().optional().nullable(),
    first_name: nonEmptyString,
    last_name: nonEmptyString,
    email,
    phone: z.string().optional().nullable(),
    position: z.string().optional().nullable(),
    commission_percentage: z.coerce.number().optional(),
    role: z.string().optional().nullable(),
    department: z.string().optional().nullable(),
    date_of_joining: z.string().optional().nullable(),
    salary: z.coerce.number().optional(),
    status: z.string().optional().nullable(),
    employee_id: z.string().optional().nullable(),
    reporting_manager_id: z.string().uuid().optional().nullable(),
    is_active: z.boolean().optional(),
  }),
  adminAgencyStaffUpdate: atLeastOne(
    z.object({
      agency_id: z.string().uuid().optional().nullable(),
      first_name: nonEmptyString.optional(),
      last_name: nonEmptyString.optional(),
      email: email.optional(),
      phone: z.string().optional().nullable(),
      position: z.string().optional().nullable(),
      commission_percentage: z.coerce.number().optional(),
      role: z.string().optional().nullable(),
      department: z.string().optional().nullable(),
      date_of_joining: z.string().optional().nullable(),
      salary: z.coerce.number().optional(),
      status: z.string().optional().nullable(),
      employee_id: z.string().optional().nullable(),
      reporting_manager_id: z.string().uuid().optional().nullable(),
      is_active: z.boolean().optional(),
    })
  ),
  adminAgencyServiceCreate: z.object({
    agency_id: z.string().uuid().optional().nullable(),
    service_name: nonEmptyString,
    description: z.string().optional().nullable(),
    rate: z.coerce.number().optional(),
    rate_type: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    category: z.string().optional().nullable(),
    base_price: z.coerce.number().optional(),
    commission_rate: z.coerce.number().optional(),
    duration: z.string().optional().nullable(),
    availability: z.string().optional().nullable(),
    requirements: z.string().optional().nullable(),
    target_market: z.string().optional().nullable(),
    features: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
  }),
  adminAgencyServiceUpdate: atLeastOne(
    z.object({
      agency_id: z.string().uuid().optional().nullable(),
      service_name: nonEmptyString.optional(),
      description: z.string().optional().nullable(),
      rate: z.coerce.number().optional(),
      rate_type: z.string().optional().nullable(),
      status: z.string().optional().nullable(),
      category: z.string().optional().nullable(),
      base_price: z.coerce.number().optional(),
      commission_rate: z.coerce.number().optional(),
      duration: z.string().optional().nullable(),
      availability: z.string().optional().nullable(),
      requirements: z.string().optional().nullable(),
      target_market: z.string().optional().nullable(),
      features: z.array(z.string()).optional(),
      tags: z.array(z.string()).optional(),
    })
  ),
  adminAgencyFinanceCreate: z.object({
    agency_id: z.string().uuid().optional().nullable(),
    date: nonEmptyString,
    type: nonEmptyString,
    category: nonEmptyString,
    amount: z.coerce.number(),
    description: z.string().optional().nullable(),
    status: nonEmptyString,
    payment_method: z.string().optional().nullable(),
    reference: z.string().optional().nullable(),
  }),
  adminAgencyFinanceUpdate: atLeastOne(
    z.object({
      agency_id: z.string().uuid().optional().nullable(),
      date: nonEmptyString.optional(),
      type: nonEmptyString.optional(),
      category: nonEmptyString.optional(),
      amount: z.coerce.number().optional(),
      description: z.string().optional().nullable(),
      status: nonEmptyString.optional(),
      payment_method: z.string().optional().nullable(),
      reference: z.string().optional().nullable(),
    })
  ),
  adminAgencyDocumentCreate: z.object({
    agency_id: z.string().uuid().optional().nullable(),
    name: nonEmptyString,
    category: nonEmptyString,
    type: nonEmptyString,
    description: z.string().optional().nullable(),
    file_url: z.string().optional().nullable(),
    file_size: z.coerce.number().optional(),
    file_type: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    access: z.string().optional().nullable(),
    retention: z.string().optional().nullable(),
    version: z.string().optional().nullable(),
    tags: z.array(z.string()).optional(),
    reminder_days: z.coerce.number().optional(),
    is_confidential: z.boolean().optional(),
    requires_approval: z.boolean().optional(),
    auto_archive: z.boolean().optional(),
    expiry_date: z.string().optional().nullable(),
    upload_date: z.string().optional().nullable(),
    last_modified: z.string().optional().nullable(),
    uploaded_by_name: z.string().optional().nullable(),
    file_type_display: z.string().optional().nullable(),
  }),
  adminAgencyDocumentUpdate: atLeastOne(
    z.object({
      agency_id: z.string().uuid().optional().nullable(),
      name: nonEmptyString.optional(),
      category: nonEmptyString.optional(),
      type: nonEmptyString.optional(),
      description: z.string().optional().nullable(),
      file_url: z.string().optional().nullable(),
      file_size: z.coerce.number().optional(),
      file_type: z.string().optional().nullable(),
      status: z.string().optional().nullable(),
      access: z.string().optional().nullable(),
      retention: z.string().optional().nullable(),
      version: z.string().optional().nullable(),
      tags: z.array(z.string()).optional(),
      reminder_days: z.coerce.number().optional(),
      is_confidential: z.boolean().optional(),
      requires_approval: z.boolean().optional(),
      auto_archive: z.boolean().optional(),
      expiry_date: z.string().optional().nullable(),
      upload_date: z.string().optional().nullable(),
      last_modified: z.string().optional().nullable(),
      uploaded_by_name: z.string().optional().nullable(),
      file_type_display: z.string().optional().nullable(),
    })
  ),
  adminExpressPayConfigQuery: z.object({
    mode: z.enum(['test', 'live']).optional(),
    scope: z.enum(['global', 'community']).optional(),
    community_id: z.string().uuid().optional(),
  }),
  adminExpressPayConfigUpsert: z
    .object({
      mode: z.enum(['test', 'live']),
      scope: z.enum(['global', 'community']).default('global'),
      community_id: z.string().uuid().optional().nullable(),
      is_enabled: z.boolean(),
      currency: optionalString,
      callback_path: optionalString,
      webhook_url: z.string().optional().nullable(),
      submit_url: z.string().optional().nullable(),
      query_url: z.string().optional().nullable(),
      checkout_url: z.string().optional().nullable(),
      merchant_id: z.string().optional().nullable(),
      api_key: z.string().optional().nullable(),
    })
    .superRefine((value, ctx) => {
      if (value.scope === 'community' && !value.community_id) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['community_id'],
          message: 'community_id is required when scope is community',
        });
      }
    }),
  adminExpressPayConfigTest: z
    .object({
      mode: z.enum(['test', 'live']).default('test'),
      scope: z.enum(['global', 'community']).default('global'),
      community_id: z.string().uuid().optional().nullable(),
    })
    .superRefine((value, ctx) => {
      if (value.scope === 'community' && !value.community_id) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ['community_id'],
          message: 'community_id is required when scope is community',
        });
      }
    }),
  adminSmtpSettingsUpdate: z.object({
    smtp_host: optionalString,
    smtp_port: z.coerce.number().int().positive().optional(),
    smtp_username: optionalString,
    smtp_password: optionalString,
    smtp_encryption: optionalString,
    smtp_from_email: optionalString,
    smtp_from_name: optionalString,
    smtp_timeout: z.coerce.number().int().positive().optional(),
    smtp_enable_ssl: z.boolean().optional(),
    smtp_enable_tls: z.boolean().optional(),
    smtp_test_mode: z.boolean().optional(),
  }),
  adminSmtpSettingsTest: z.object({
    smtp_host: optionalString,
    smtp_port: z.coerce.number().int().positive().optional(),
    smtp_username: optionalString,
    smtp_password: optionalString,
    smtp_encryption: optionalString,
    smtp_from_email: optionalString,
    smtp_from_name: optionalString,
    smtp_timeout: z.coerce.number().int().positive().optional(),
    smtp_enable_ssl: z.boolean().optional(),
    smtp_enable_tls: z.boolean().optional(),
    smtp_test_mode: z.boolean().optional(),
  }),
  adminIntegrationSettingsUpdate: z.object({
    openai_api_key: optionalString,
    openai_organization_id: optionalString,
    anthropic_api_key: optionalString,
    google_ai_api_key: optionalString,
    azure_openai_endpoint: optionalString,
    azure_openai_key: optionalString,
    huggingface_api_key: optionalString,
    sms_provider: optionalString,
    sms_api_key: optionalString,
    email_provider: optionalString,
    email_api_key: optionalString,
    whatsapp_business_api_key: optionalString,
    telegram_bot_token: optionalString,
    slack_webhook_url: optionalString,
    razorpay_key_id: optionalString,
    razorpay_key_secret: optionalString,
    stripe_public_key: optionalString,
    stripe_secret_key: optionalString,
    paypal_client_id: optionalString,
    paypal_client_secret: optionalString,
    aws_access_key: optionalString,
    aws_secret_key: optionalString,
    aws_region: optionalString,
    aws_bucket_name: optionalString,
    google_cloud_key: optionalString,
    azure_storage_key: optionalString,
    firebase_config: optionalString,
    pusher_app_id: optionalString,
    pusher_key: optionalString,
    pusher_secret: optionalString,
    ai_chat_enabled: z.boolean().optional(),
    ai_maintenance_predictions: z.boolean().optional(),
    ai_document_processing: z.boolean().optional(),
    smart_notifications: z.boolean().optional(),
    automated_billing: z.boolean().optional(),
    real_time_analytics: z.boolean().optional(),
  }),
  adminIntegrationSettingsTest: z.object({
    service: z.enum([
      'openai_api_key',
      'anthropic_api_key',
      'google_ai_api_key',
      'azure_openai_key',
      'huggingface_api_key',
      'sms_api_key',
      'email_api_key',
      'whatsapp_business_api_key',
      'telegram_bot_token',
      'slack_webhook_url',
      'razorpay_key_id',
      'stripe_public_key',
      'paypal_client_id',
      'aws_access_key',
      'google_cloud_key',
      'azure_storage_key',
      'firebase_config',
      'pusher_key',
    ]),
    value: z.any().optional(),
  }),
  adminPushSettingsUpdate: z.object({
    firebase_enabled: z.boolean().optional(),
    firebase_server_key: optionalString,
    firebase_sender_id: optionalString,
    firebase_api_key: optionalString,
    firebase_project_id: optionalString,
    push_maintenance_requests: z.boolean().optional(),
    push_payment_reminders: z.boolean().optional(),
    push_visitor_approvals: z.boolean().optional(),
    push_emergency_alerts: z.boolean().optional(),
    push_community_announcements: z.boolean().optional(),
    push_complaint_updates: z.boolean().optional(),
    push_amenity_bookings: z.boolean().optional(),
    push_service_updates: z.boolean().optional(),
    admin_push_new_users: z.boolean().optional(),
    admin_push_new_complaints: z.boolean().optional(),
    admin_push_maintenance_requests: z.boolean().optional(),
    admin_push_payment_received: z.boolean().optional(),
    admin_push_emergency_alerts: z.boolean().optional(),
    push_sound_enabled: z.boolean().optional(),
    push_vibration_enabled: z.boolean().optional(),
    push_badge_enabled: z.boolean().optional(),
    push_quiet_hours_enabled: z.boolean().optional(),
    push_quiet_start_time: optionalString,
    push_quiet_end_time: optionalString,
    default_push_title: optionalString,
    default_push_message: optionalString,
    push_click_action: optionalString,
  }),
  adminPushSettingsTest: z.object({
    firebase_enabled: z.boolean().optional(),
    firebase_server_key: optionalString,
    firebase_sender_id: optionalString,
    firebase_api_key: optionalString,
    firebase_project_id: optionalString,
    push_sound_enabled: z.boolean().optional(),
    push_vibration_enabled: z.boolean().optional(),
    push_badge_enabled: z.boolean().optional(),
    push_quiet_hours_enabled: z.boolean().optional(),
    push_quiet_start_time: optionalString,
    push_quiet_end_time: optionalString,
    default_push_title: optionalString,
    default_push_message: optionalString,
    push_click_action: optionalString,
  }),
  adminSmsSettingsUpdate: z.object({
    sms_provider: optionalString,
    twilio_account_sid: optionalString,
    twilio_auth_token: optionalString,
    twilio_phone_number: optionalString,
    aws_access_key_id: optionalString,
    aws_secret_access_key: optionalString,
    aws_region: optionalString,
    textlocal_api_key: optionalString,
    textlocal_sender: optionalString,
    msg91_api_key: optionalString,
    msg91_sender_id: optionalString,
    msg91_route: optionalString,
    default_country_code: optionalString,
    rate_limit_per_minute: z.coerce.number().int().positive().optional(),
    sms_timeout: z.coerce.number().int().positive().optional(),
    enable_delivery_reports: z.boolean().optional(),
    test_mode: z.boolean().optional(),
    enable_otp_sms: z.boolean().optional(),
    enable_alert_sms: z.boolean().optional(),
    enable_reminder_sms: z.boolean().optional(),
    enable_emergency_sms: z.boolean().optional(),
  }),
  adminSmsSettingsTest: z.object({
    sms_provider: optionalString,
    twilio_account_sid: optionalString,
    twilio_auth_token: optionalString,
    twilio_phone_number: optionalString,
    aws_access_key_id: optionalString,
    aws_secret_access_key: optionalString,
    aws_region: optionalString,
    textlocal_api_key: optionalString,
    textlocal_sender: optionalString,
    msg91_api_key: optionalString,
    msg91_sender_id: optionalString,
    msg91_route: optionalString,
  }),
  adminPaymentGatewaySettingsUpdate: z.object({
    razorpay_enabled: z.boolean().optional(),
    razorpay_key_id: optionalString,
    razorpay_key_secret: optionalString,
    razorpay_webhook_secret: optionalString,
    razorpay_mode: optionalString,
    stripe_enabled: z.boolean().optional(),
    stripe_publishable_key: optionalString,
    stripe_secret_key: optionalString,
    stripe_webhook_secret: optionalString,
    stripe_mode: optionalString,
    paypal_enabled: z.boolean().optional(),
    paypal_client_id: optionalString,
    paypal_client_secret: optionalString,
    paypal_webhook_id: optionalString,
    paypal_mode: optionalString,
    paytm_enabled: z.boolean().optional(),
    paytm_merchant_id: optionalString,
    paytm_merchant_key: optionalString,
    paytm_website: optionalString,
    paytm_mode: optionalString,
    bank_transfer_enabled: z.boolean().optional(),
    bank_name: optionalString,
    account_number: optionalString,
    ifsc_code: optionalString,
    account_holder_name: optionalString,
    payment_currency: optionalString,
    payment_timeout: z.coerce.number().int().positive().optional(),
    auto_refund_enabled: z.boolean().optional(),
    partial_payment_enabled: z.boolean().optional(),
  }),
  adminPaymentMethodSettingsUpdate: z.object({
    credit_card_enabled: z.boolean().optional(),
    debit_card_enabled: z.boolean().optional(),
    net_banking_enabled: z.boolean().optional(),
    expresspay_enabled: z.boolean().optional(),
    wallet_enabled: z.boolean().optional(),
    bank_transfer_enabled: z.boolean().optional(),
    cash_enabled: z.boolean().optional(),
    cheque_enabled: z.boolean().optional(),
    min_payment_amount: z.coerce.number().nonnegative().optional(),
    max_payment_amount: z.coerce.number().nonnegative().optional(),
    daily_payment_limit: z.coerce.number().nonnegative().optional(),
    monthly_payment_limit: z.coerce.number().nonnegative().optional(),
    auto_capture_enabled: z.boolean().optional(),
    partial_payments_enabled: z.boolean().optional(),
    recurring_payments_enabled: z.boolean().optional(),
    refund_enabled: z.boolean().optional(),
    payment_instructions: z.string().optional(),
    payment_terms: z.string().optional(),
  }),
  adminPaymentFeeSettingsUpdate: z.object({
    credit_card_fee_percentage: z.coerce.number().min(0).max(10).optional(),
    credit_card_fee_fixed: z.coerce.number().nonnegative().optional(),
    debit_card_fee_percentage: z.coerce.number().min(0).max(10).optional(),
    debit_card_fee_fixed: z.coerce.number().nonnegative().optional(),
    expresspay_fee_percentage: z.coerce.number().min(0).max(10).optional(),
    expresspay_fee_fixed: z.coerce.number().nonnegative().optional(),
    net_banking_fee_percentage: z.coerce.number().min(0).max(10).optional(),
    net_banking_fee_fixed: z.coerce.number().nonnegative().optional(),
    wallet_fee_percentage: z.coerce.number().min(0).max(10).optional(),
    wallet_fee_fixed: z.coerce.number().nonnegative().optional(),
    processing_fee_enabled: z.boolean().optional(),
    processing_fee_percentage: z.coerce.number().min(0).max(10).optional(),
    processing_fee_fixed: z.coerce.number().nonnegative().optional(),
    processing_fee_max_amount: z.coerce.number().nonnegative().optional(),
    convenience_fee_enabled: z.boolean().optional(),
    convenience_fee_percentage: z.coerce.number().min(0).max(10).optional(),
    convenience_fee_fixed: z.coerce.number().nonnegative().optional(),
    late_payment_fee_enabled: z.boolean().optional(),
    late_payment_fee_percentage: z.coerce.number().min(0).max(50).optional(),
    late_payment_fee_fixed: z.coerce.number().nonnegative().optional(),
    late_payment_grace_period: z.coerce.number().int().min(0).max(30).optional(),
    fee_bearer: optionalString,
    fee_calculation_method: optionalString,
    minimum_fee_amount: z.coerce.number().nonnegative().optional(),
    maximum_fee_amount: z.coerce.number().nonnegative().optional(),
  }),
  adminBusinessSettingsUpdate: z.object({
    default_currency: optionalString,
    maintenance_fee: z.coerce.number().nonnegative().optional(),
    late_payment_penalty_percentage: z.coerce.number().min(0).max(100).optional(),
    payment_reminder_days: z.coerce.number().int().min(1).max(30).optional(),
    payment_due_grace_period_days: z.coerce.number().int().min(0).max(30).optional(),
    visitor_pass_expiry_hours: z.coerce.number().int().min(1).max(168).optional(),
    max_visitors_per_unit: z.coerce.number().int().min(1).max(20).optional(),
    visitor_pre_approval_required: z.boolean().optional(),
    maintenance_request_auto_approve: z.boolean().optional(),
    amenity_booking_enabled: z.boolean().optional(),
    complaint_system_enabled: z.boolean().optional(),
    emergency_contacts_enabled: z.boolean().optional(),
    digital_notice_board_enabled: z.boolean().optional(),
  }),
  adminRegionalSettingsUpdate: z.object({
    timezone: optionalString,
    dateFormat: optionalString,
    timeFormat: optionalString,
    weekStartDay: optionalString,
    currency: optionalString,
    currencyPosition: optionalString,
    numberFormat: optionalString,
    primaryLanguage: optionalString,
    supportedLanguages: z.array(z.string()).optional(),
    rtlSupport: z.boolean().optional(),
    addressFormat: optionalString,
    phoneFormat: optionalString,
    postalCodeFormat: optionalString,
    gstEnabled: z.boolean().optional(),
    vatEnabled: z.boolean().optional(),
    gdprCompliance: z.boolean().optional(),
    cookieConsent: z.boolean().optional(),
    dataLocalization: z.boolean().optional(),
  }),
  adminSecurityPrivacySettingsUpdate: z.object({
    terms_url: optionalString,
    privacy_url: optionalString,
    refund_policy_url: optionalString,
    data_retention_policy_url: optionalString,
    password_min_length: z.coerce.number().int().min(6).max(32).optional(),
    password_require_uppercase: z.boolean().optional(),
    password_require_lowercase: z.boolean().optional(),
    password_require_numbers: z.boolean().optional(),
    password_require_symbols: z.boolean().optional(),
    login_attempt_limit: z.coerce.number().int().min(3).max(10).optional(),
    account_lockout_duration_minutes: z.coerce.number().int().min(5).max(1440).optional(),
    two_factor_auth_enabled: z.boolean().optional(),
    data_encryption_enabled: z.boolean().optional(),
    gdpr_compliance_enabled: z.boolean().optional(),
    data_retention_days: z.coerce.number().int().min(30).max(2555).optional(),
  }),
  adminGeneralSystemSettingsUpdate: z.object({
    admin_dashboard_refresh_minutes: z.coerce.number().int().min(1).max(60).optional(),
    auto_logout_minutes: z.coerce.number().int().min(5).max(480).optional(),
    max_file_upload_size_mb: z.coerce.number().int().min(1).max(100).optional(),
    session_timeout_minutes: z.coerce.number().int().min(15).max(1440).optional(),
    max_concurrent_sessions: z.coerce.number().int().min(1).max(10).optional(),
    data_backup_frequency: optionalString,
    log_retention_days: z.coerce.number().int().min(7).max(365).optional(),
    enable_real_time_notifications: z.boolean().optional(),
    enable_analytics: z.boolean().optional(),
    enable_audit_logs: z.boolean().optional(),
    enable_maintenance_mode: z.boolean().optional(),
  }),

  systemSettingsQuery: z.object({
    category: optionalString,
    subcategory: optionalString,
    raw: booleanFromString.optional(),
  }),
  systemSettingsExistsQuery: z.object({
    category: optionalString,
    subcategory: optionalString,
  }),
  systemSettingsUpsert: z.object({
    category: optionalString,
    subcategory: optionalString,
    settings: nonEmptyObject,
    descriptions: z.record(z.any()).optional(),
    sensitivities: z.record(z.any()).optional(),
  }),
  systemSettingsDeleteParams: z.object({ key: nonEmptyString }),
  systemSettingsDeleteQuery: z.object({
    category: optionalString,
    subcategory: optionalString,
  }),

  roleParams: z.object({ role: nonEmptyString }),
  rolePermissions: z.object({
    permissions: z.array(nonEmptyString).nonempty(),
  }),

  visitorPassCreate: z.object({
    visitor_name: nonEmptyString,
    visitor_phone: nonEmptyString,
    unit_id: nonEmptyString,
    purpose: nonEmptyString,
    expected_time: nonEmptyString,
    valid_until: nonEmptyString,
  }),
  visitorPassesQuery: z.object({
    unitId: nonEmptyString,
  }),
  visitorPassStatusParams: idParam,
  entryLogCreate: z.object({
    visitor_name: nonEmptyString,
    unit_id: nonEmptyString,
    entry_time: nonEmptyString,
    purpose: nonEmptyString,
    exit_time: z.string().optional(),
    guard_id: z.string().optional(),
  }),

  maintenanceQuery: z.object({
    unitId: nonEmptyString,
  }),
  maintenanceCreate: z.object({
    unit_id: nonEmptyString,
    title: nonEmptyString,
    description: nonEmptyString,
    priority: optionalString,
    requested_by: optionalString,
  }),
  maintenanceUpdate: atLeastOne(
    z.object({
      status: optionalString,
      assigned_to: optionalString,
      completed_at: optionalString,
      notes: optionalString,
    })
  ),

  complaintQuery: z.object({
    unitId: nonEmptyString,
  }),
  complaintCreate: z.object({
    unit_id: nonEmptyString,
    subject: nonEmptyString,
    details: nonEmptyString,
    priority: optionalString,
    category_id: optionalString,
    created_by: optionalString,
  }),
  complaintUpdate: atLeastOne(
    z.object({
      status: optionalString,
      priority: optionalString,
      category: optionalString,
      subject: optionalString,
      details: optionalString,
      assigned_to: optionalString,
      resolution: optionalString,
      resolution_notes: optionalString,
      resolved_at: optionalString,
      in_progress_at: optionalString,
      resolved_by_profile_id: optionalString,
      updated_at: optionalString,
    })
  ),

  messageQuery: z.object({
    withUser: nonEmptyString,
  }),
  messageCreate: z.object({
    from_user: nonEmptyString,
    to_user: nonEmptyString,
    body: nonEmptyString,
    message_type: z.enum(['text', 'file']).optional(),
  }),

  noticeQuery: z.object({
    societyId: nonEmptyString,
  }),

  paymentStatsParams: z.object({ societyId: nonEmptyString }),
  paymentStatsQuery: z.object({
    timeFrame: z.enum(['week', 'month', 'year']).optional(),
  }),
  paymentSocietyParams: z.object({ societyId: nonEmptyString }),
  paymentUnitParams: z.object({ unitId: nonEmptyString }),
  paymentIdParams: idParam,
  paymentQueryOptions: z.object({
    page: z.coerce.number().int().min(1).optional(),
    limit: z.coerce.number().int().min(1).max(200).optional(),
    sortBy: optionalString,
    sortOrder: z.enum(['asc', 'desc']).optional(),
    status: optionalString,
    startDate: optionalString,
    endDate: optionalString,
    paymentType: optionalString,
    unitId: optionalString,
  }),
  paymentCreate: nonEmptyObject,
  paymentUpdate: nonEmptyObject,
  paymentStatusUpdate: z.object({
    status: nonEmptyString,
    notes: z.string().optional(),
  }),
  adminPaymentChargeCatalogQuery: z.object({
    include_inactive: booleanFromString.optional(),
  }),
  adminPaymentChargeTemplateListQuery: z.object({
    scope_level: paymentChargeScope.optional(),
    agency_id: optionalString,
    community_id: optionalString,
    include_inactive: booleanFromString.optional(),
  }),
  adminPaymentChargeTemplateTarget: paymentChargeTemplateTargetSchema,
  adminPaymentChargeTemplateCreate: z.object({
    scope_level: paymentChargeScope,
    agency_id: optionalString.nullable(),
    community_id: optionalString.nullable(),
    name: nonEmptyString,
    charge_code: nonEmptyString,
    catalog_key: nonEmptyString,
    category: nonEmptyString,
    charge_type: paymentChargeType,
    amount: z.coerce.number().nonnegative(),
    currency_code: optionalString.nullable(),
    billing_frequency: paymentChargeFrequency,
    billing_anchor_day: z.coerce.number().int().min(1).max(31).optional().nullable(),
    billing_anchor_month: z.coerce.number().int().min(1).max(12).optional().nullable(),
    start_date: optionalString.nullable(),
    due_offset_days: z.coerce.number().int().min(0).max(365).optional().nullable(),
    grace_period_days: z.coerce.number().int().min(0).max(365).optional().nullable(),
    late_fee_type: paymentChargeLateFeeType.optional().nullable(),
    late_fee_value: z.coerce.number().min(0).optional().nullable(),
    auto_issue: z.boolean().optional(),
    requires_approval: z.boolean().optional(),
    is_active: z.boolean().optional(),
    description: z.string().optional().nullable(),
    metadata: z.record(z.any()).optional().nullable(),
    targets: z.array(paymentChargeTemplateTargetSchema).optional(),
  }),
  adminPaymentChargeTemplateUpdate: atLeastOne(
    z.object({
      scope_level: paymentChargeScope.optional(),
      agency_id: optionalString.nullable(),
      community_id: optionalString.nullable(),
      name: optionalString,
      charge_code: optionalString,
      catalog_key: optionalString,
      category: optionalString,
      charge_type: paymentChargeType.optional(),
      amount: z.coerce.number().nonnegative().optional(),
      currency_code: optionalString.nullable(),
      billing_frequency: paymentChargeFrequency.optional(),
      billing_anchor_day: z.coerce.number().int().min(1).max(31).optional().nullable(),
      billing_anchor_month: z.coerce.number().int().min(1).max(12).optional().nullable(),
      start_date: optionalString.nullable(),
      due_offset_days: z.coerce.number().int().min(0).max(365).optional().nullable(),
      grace_period_days: z.coerce.number().int().min(0).max(365).optional().nullable(),
      late_fee_type: paymentChargeLateFeeType.optional().nullable(),
      late_fee_value: z.coerce.number().min(0).optional().nullable(),
      auto_issue: z.boolean().optional(),
      requires_approval: z.boolean().optional(),
      is_active: z.boolean().optional(),
      description: z.string().optional().nullable(),
      metadata: z.record(z.any()).optional().nullable(),
      targets: z.array(paymentChargeTemplateTargetSchema).optional(),
    })
  ),
  adminPaymentChargeTemplatePreviewBody: z.object({
    community_id: optionalString.nullable(),
    unit_ids: z.array(nonEmptyString).optional(),
    billing_period_start: optionalString.nullable(),
    billing_period_end: optionalString.nullable(),
    due_date: optionalString.nullable(),
    run_mode: z.enum(['manual', 'scheduled']).optional(),
  }),
  adminPaymentChargeRunListQuery: z.object({
    community_id: optionalString,
    template_id: optionalString,
    status: paymentChargeRunStatus.optional(),
  }),
  adminPaymentChargeRunDueBody: z.object({
    community_id: optionalString.nullable(),
    agency_id: optionalString.nullable(),
  }),
  internalPayoutRecomputeBody: z.object({
    community_id: optionalString.nullable(),
    agency_id: optionalString.nullable(),
    limit: z.coerce.number().int().positive().max(1000).optional(),
  }),
  internalPayoutReleaseBody: z.object({
    community_id: optionalString.nullable(),
    agency_id: optionalString.nullable(),
    stale_hours: z.coerce.number().positive().max(720).optional(),
    limit: z.coerce.number().int().positive().max(500).optional(),
  }),
  adminPayoutScopeQuery: z.object({
    agency_id: optionalString,
    community_id: optionalString,
  }),
  adminPersonalHubDashboardQuery: z.object({
    period: z.enum(['7', '30', '90', '365']).optional(),
    recent_limit: z.coerce.number().int().min(1).max(25).optional(),
  }),
  adminPersonalHubReportsQuery: z.object({
    period: z.enum(['7', '30', '90', '365']).optional(),
    service_types: optionalString,
    statuses: optionalString,
    providers: optionalString,
    search: optionalString,
    min_amount: z.coerce.number().min(0).optional(),
    max_amount: z.coerce.number().min(0).optional(),
    limit: z.coerce.number().int().min(50).max(1000).optional(),
  }),
  adminPayoutDestinationCreate: z.object({
    agency_id: optionalString.nullable(),
    community_id: optionalString.nullable(),
    destination_type: payoutDestinationType,
    label: nonEmptyString,
    account_name: z.string().optional().nullable(),
    account_number: z.string().optional().nullable(),
    bank_name: z.string().optional().nullable(),
    bank_code: z.string().optional().nullable(),
    mobile_network: z.string().optional().nullable(),
    mobile_number: z.string().optional().nullable(),
    currency_code: optionalString.nullable(),
    is_default: z.boolean().optional(),
    is_verified: z.boolean().optional(),
    status: z.enum(['active', 'inactive', 'disabled']).optional(),
    metadata: z.record(z.any()).optional().nullable(),
  }),
  adminPayoutDestinationUpdate: atLeastOne(
    z.object({
      label: z.string().optional(),
      account_name: z.string().optional().nullable(),
      account_number: z.string().optional().nullable(),
      bank_name: z.string().optional().nullable(),
      bank_code: z.string().optional().nullable(),
      mobile_network: z.string().optional().nullable(),
      mobile_number: z.string().optional().nullable(),
      is_default: z.boolean().optional(),
      is_verified: z.boolean().optional(),
      status: z.enum(['active', 'inactive', 'disabled']).optional(),
      metadata: z.record(z.any()).optional().nullable(),
    })
  ),
  adminPayoutRuleUpsert: z.object({
    id: optionalString.nullable(),
    agency_id: optionalString.nullable(),
    community_id: optionalString.nullable(),
    effective_from: optionalString.nullable(),
    community_share_mode: payoutRuleShareMode,
    community_share_value: z.coerce.number().min(0),
    agency_share_mode: payoutRuleAgencyShareMode,
    agency_share_value: z.coerce.number().min(0).optional().nullable(),
    platform_fee_mode: payoutRuleShareMode,
    platform_fee_value: z.coerce.number().min(0).optional().nullable(),
    is_active: z.boolean().optional(),
  }),
  adminPayoutRequestCreate: z.object({
    agency_id: optionalString.nullable(),
    community_id: optionalString.nullable(),
    destination_id: nonEmptyString,
    requested_amount: z.coerce.number().positive(),
    notes: z.string().optional().nullable(),
  }),
  adminPayoutRequestActionParams: z.object({
    id: nonEmptyString,
    action: payoutRequestAction,
  }),
  adminPayoutRequestActionBody: z.object({
    notes: z.string().optional().nullable(),
    failure_reason: z.string().optional().nullable(),
  }),
  expressPayInitiate: z.object({
    amount: z.coerce.number().positive(),
    currency: optionalString,
    currency_code: optionalString,
    payment_type: nonEmptyString,
    payment_method: nonEmptyString,
    unit_id: nonEmptyString,
    description: optionalString,
    booking_id: optionalString,
    source_type: optionalString,
    source_id: optionalString,
    obligation_id: optionalString,
    metadata: z.record(z.any()).optional(),
    idempotency_key: optionalString,
  }),
  expressPayStatusParams: z.object({
    paymentId: nonEmptyString,
  }),
  expressPayVerify: z
    .object({
      payment_id: optionalString,
      token: optionalString,
      order_id: optionalString,
    })
    .refine((value) => Boolean(value.payment_id || value.token || value.order_id), {
      message: 'payment_id, token, or order_id is required',
      path: ['payment_id'],
    }),

  guardCreate: z
    .object({
      first_name: nonEmptyString,
      last_name: nonEmptyString,
      email,
      phone: optionalString,
      guard_phone: optionalString,
      date_of_birth: optionalString,
      address: optionalString,
      avatar_url: optionalString,
      society_id: optionalString,
      shift_type: z.enum(['morning', 'evening', 'night']).optional(),
      shift_start_time: optionalString,
      shift_end_time: optionalString,
      gate_assignment: optionalString,
      license_number: optionalString,
      employment_date: optionalString,
      salary: z.number().optional(),
      emergency_contact_name: optionalString,
      emergency_contact_phone: optionalString,
      status: z.enum(['active', 'inactive', 'suspended']).optional(),
    })
    .passthrough(),
  guardUpdate: atLeastOne(
    z
      .object({
        first_name: optionalString,
        last_name: optionalString,
        email,
        phone: optionalString,
        guard_phone: optionalString,
        date_of_birth: optionalString,
        address: optionalString,
        avatar_url: optionalString,
        society_id: optionalString,
        shift_type: z.enum(['morning', 'evening', 'night']).optional(),
        shift_start_time: optionalString,
        shift_end_time: optionalString,
        gate_assignment: optionalString,
        license_number: optionalString,
        employment_date: optionalString,
        salary: z.number().optional(),
        emergency_contact_name: optionalString,
        emergency_contact_phone: optionalString,
        status: z.enum(['active', 'inactive', 'suspended']).optional(),
      })
      .passthrough()
  ),
  guardIdParams: idParam,
  guardListQuery: pageLimitQuery.extend({
    society_id: optionalString,
    status: optionalString,
  }).merge(withSearchQuery),
  guardPhoneQuery: z.object({
    phone: nonEmptyString,
  }),

  unitCreate: z
    .object({
      block: nonEmptyString,
      number: nonEmptyString,
      floor: z.coerce.number().int(),
      society_id: nonEmptyString,
      ownership_type: z.enum(['owned', 'rented']),
      floor_area: z.number().optional(),
      bedrooms: z.number().int().optional(),
      bathrooms: z.number().int().optional(),
      balconies: z.number().int().optional(),
      parking_slots: z.number().int().optional(),
      owner_id: optionalString,
      owner_name: optionalString,
      owner_email: z.string().email().optional(),
      owner_phone: optionalString,
      tenant_id: optionalString,
      tenant_name: optionalString,
      tenant_email: z.string().email().optional(),
      tenant_phone: optionalString,
      is_occupied: z.boolean().optional(),
      occupancy_start_date: optionalString,
      occupancy_end_date: optionalString,
      status: z.enum(['active', 'inactive', 'suspended', 'pending']).optional(),
    })
    .passthrough(),
  unitUpdate: atLeastOne(
    z
      .object({
        block: optionalString,
        number: optionalString,
        floor: z.coerce.number().int().optional(),
        society_id: optionalString,
        ownership_type: z.enum(['owned', 'rented']).optional(),
        floor_area: z.number().optional(),
        bedrooms: z.number().int().optional(),
        bathrooms: z.number().int().optional(),
        balconies: z.number().int().optional(),
        parking_slots: z.number().int().optional(),
        owner_id: optionalString,
        owner_name: optionalString,
        owner_email: z.string().email().optional(),
        owner_phone: optionalString,
        tenant_id: optionalString,
        tenant_name: optionalString,
        tenant_email: z.string().email().optional(),
        tenant_phone: optionalString,
        is_occupied: z.boolean().optional(),
        occupancy_start_date: optionalString,
        occupancy_end_date: optionalString,
        status: z.enum(['active', 'inactive', 'suspended', 'pending']).optional(),
      })
      .passthrough()
  ),
  unitIdParams: idParam,
  unitListQuery: pageLimitQuery.merge(withSearchQuery).extend({
    society_id: optionalString,
    block: optionalString,
    ownership_type: z.enum(['owned', 'rented']).optional(),
    is_occupied: booleanFromString.optional(),
  }),
  unitPhoneQuery: z.object({
    phone: nonEmptyString,
  }),

  amenityCreate: z
    .object({
      name: nonEmptyString,
      amenity_type: nonEmptyString,
      society_id: nonEmptyString,
      description: optionalString,
      location: optionalString,
      capacity: z.number().int().optional(),
      is_active: z.boolean().optional(),
      is_paid: z.boolean().optional(),
      price: z.number().optional(),
      price_per_hour: z.number().optional(),
      advance_booking_hours: z.number().int().optional(),
      max_advance_booking_days: z.number().int().optional(),
      minimum_booking_duration_hours: z.number().int().optional(),
      maximum_booking_duration_hours: z.number().int().optional(),
      booking_slots_per_day: z.number().int().optional(),
      booking_cancellation_hours: z.number().int().optional(),
      contact_person: optionalString,
      contact_phone: optionalString,
      availability_schedule: z.any().optional(),
      maintenance_schedule: z.any().optional(),
      rules: optionalString,
      images: z.array(z.string()).optional(),
    })
    .passthrough(),
  amenityUpdate: atLeastOne(
    z
      .object({
        name: optionalString,
        amenity_type: optionalString,
        society_id: optionalString,
        description: optionalString,
        location: optionalString,
        capacity: z.number().int().optional(),
        is_active: z.boolean().optional(),
        is_paid: z.boolean().optional(),
        price: z.number().optional(),
        price_per_hour: z.number().optional(),
        advance_booking_hours: z.number().int().optional(),
        max_advance_booking_days: z.number().int().optional(),
        minimum_booking_duration_hours: z.number().int().optional(),
        maximum_booking_duration_hours: z.number().int().optional(),
        booking_slots_per_day: z.number().int().optional(),
        booking_cancellation_hours: z.number().int().optional(),
        contact_person: optionalString,
        contact_phone: optionalString,
        availability_schedule: z.any().optional(),
        maintenance_schedule: z.any().optional(),
        rules: optionalString,
        images: z.array(z.string()).optional(),
      })
      .passthrough()
  ),
  amenityIdParams: idParam,
  amenityListQuery: pageLimitQuery.merge(withSearchQuery).extend({
    society_id: optionalString,
    amenity_type: optionalString,
    is_active: booleanFromString.optional(),
    is_paid: booleanFromString.optional(),
  }),
  amenityPhoneQuery: z.object({
    phone: nonEmptyString,
  }),

  societyListQuery: pageLimitQuery.merge(withSearchQuery).extend({
    sortBy: optionalString,
    sortOrder: z.enum(['asc', 'desc']).optional(),
    type: optionalString,
  }),
  societyIdParams: idParam,
  unitBySocietyParams: idParam,
};
