-- Phase 48: Remove inherited PUBLIC execute grants from security-definer functions.
-- Authenticated/service_role access is explicitly restored so logged-in app behavior is preserved.

revoke execute on function public."actor_profile_in_accessible_community"(target_actor_id uuid) from public;
grant execute on function public."actor_profile_in_accessible_community"(target_actor_id uuid) to authenticated;
grant execute on function public."actor_profile_in_accessible_community"(target_actor_id uuid) to service_role;
revoke execute on function public."admin_get_all_logs"() from public;
grant execute on function public."admin_get_all_logs"() to authenticated;
grant execute on function public."admin_get_all_logs"() to service_role;
revoke execute on function public."can_access_agency"(target_agency_id uuid) from public;
grant execute on function public."can_access_agency"(target_agency_id uuid) to authenticated;
grant execute on function public."can_access_agency"(target_agency_id uuid) to service_role;
revoke execute on function public."can_access_chat_attachment"(object_name text) from public;
grant execute on function public."can_access_chat_attachment"(object_name text) to authenticated;
grant execute on function public."can_access_chat_attachment"(object_name text) to service_role;
revoke execute on function public."can_access_community"(target_community_id uuid) from public;
grant execute on function public."can_access_community"(target_community_id uuid) to authenticated;
grant execute on function public."can_access_community"(target_community_id uuid) to service_role;
revoke execute on function public."can_access_payout_agency"(target_agency_id uuid) from public;
grant execute on function public."can_access_payout_agency"(target_agency_id uuid) to authenticated;
grant execute on function public."can_access_payout_agency"(target_agency_id uuid) to service_role;
revoke execute on function public."can_access_payout_request"(target_payout_request_id uuid) from public;
grant execute on function public."can_access_payout_request"(target_payout_request_id uuid) to authenticated;
grant execute on function public."can_access_payout_request"(target_payout_request_id uuid) to service_role;
revoke execute on function public."can_access_personal_hub_transaction"(target_transaction_type text, target_transaction_id uuid) from public;
grant execute on function public."can_access_personal_hub_transaction"(target_transaction_type text, target_transaction_id uuid) to authenticated;
grant execute on function public."can_access_personal_hub_transaction"(target_transaction_type text, target_transaction_id uuid) to service_role;
revoke execute on function public."can_access_unit"(target_unit_id uuid) from public;
grant execute on function public."can_access_unit"(target_unit_id uuid) to authenticated;
grant execute on function public."can_access_unit"(target_unit_id uuid) to service_role;
revoke execute on function public."current_guard_community_id"() from public;
grant execute on function public."current_guard_community_id"() to authenticated;
grant execute on function public."current_guard_community_id"() to service_role;
revoke execute on function public."current_profile_id"() from public;
grant execute on function public."current_profile_id"() to authenticated;
grant execute on function public."current_profile_id"() to service_role;
revoke execute on function public."current_user_community_id"() from public;
grant execute on function public."current_user_community_id"() to authenticated;
grant execute on function public."current_user_community_id"() to service_role;
revoke execute on function public."current_user_role"() from public;
grant execute on function public."current_user_role"() to authenticated;
grant execute on function public."current_user_role"() to service_role;
revoke execute on function public."enforce_service_request_service_scope"() from public;
grant execute on function public."enforce_service_request_service_scope"() to authenticated;
grant execute on function public."enforce_service_request_service_scope"() to service_role;
revoke execute on function public."get_activity_logs_stats"() from public;
grant execute on function public."get_activity_logs_stats"() to authenticated;
grant execute on function public."get_activity_logs_stats"() to service_role;
revoke execute on function public."get_all_activity_logs"(user_id_param uuid) from public;
grant execute on function public."get_all_activity_logs"(user_id_param uuid) to authenticated;
grant execute on function public."get_all_activity_logs"(user_id_param uuid) to service_role;
revoke execute on function public."get_auth_users_with_last_sign_in"() from public;
grant execute on function public."get_auth_users_with_last_sign_in"() to authenticated;
grant execute on function public."get_auth_users_with_last_sign_in"() to service_role;
revoke execute on function public."get_current_profile_id"() from public;
grant execute on function public."get_current_profile_id"() to authenticated;
grant execute on function public."get_current_profile_id"() to service_role;
revoke execute on function public."get_my_role"() from public;
grant execute on function public."get_my_role"() to authenticated;
grant execute on function public."get_my_role"() to service_role;
revoke execute on function public."get_pending_visitor_passes"() from public;
grant execute on function public."get_pending_visitor_passes"() to authenticated;
grant execute on function public."get_pending_visitor_passes"() to service_role;
revoke execute on function public."get_society_units"(society_id uuid) from public;
grant execute on function public."get_society_units"(society_id uuid) to authenticated;
grant execute on function public."get_society_units"(society_id uuid) to service_role;
revoke execute on function public."guard_can_access_community"(target_community_id uuid) from public;
grant execute on function public."guard_can_access_community"(target_community_id uuid) to authenticated;
grant execute on function public."guard_can_access_community"(target_community_id uuid) to service_role;
revoke execute on function public."guard_can_access_unit"(target_unit_id uuid) from public;
grant execute on function public."guard_can_access_unit"(target_unit_id uuid) to authenticated;
grant execute on function public."guard_can_access_unit"(target_unit_id uuid) to service_role;
revoke execute on function public."guard_can_notify_user"(target_user_id uuid) from public;
grant execute on function public."guard_can_notify_user"(target_user_id uuid) to authenticated;
grant execute on function public."guard_can_notify_user"(target_user_id uuid) to service_role;
revoke execute on function public."handle_guard_assignment_scope_sync"() from public;
grant execute on function public."handle_guard_assignment_scope_sync"() to authenticated;
grant execute on function public."handle_guard_assignment_scope_sync"() to service_role;
revoke execute on function public."handle_new_auth_user"() from public;
grant execute on function public."handle_new_auth_user"() to authenticated;
grant execute on function public."handle_new_auth_user"() to service_role;
revoke execute on function public."increment_comment_likes"(comment_id uuid) from public;
grant execute on function public."increment_comment_likes"(comment_id uuid) to authenticated;
grant execute on function public."increment_comment_likes"(comment_id uuid) to service_role;
revoke execute on function public."is_admin_role"() from public;
grant execute on function public."is_admin_role"() to authenticated;
grant execute on function public."is_admin_role"() to service_role;
revoke execute on function public."is_chat_participant"(target_chat_id uuid, target_user_id uuid) from public;
grant execute on function public."is_chat_participant"(target_chat_id uuid, target_user_id uuid) to authenticated;
grant execute on function public."is_chat_participant"(target_chat_id uuid, target_user_id uuid) to service_role;
revoke execute on function public."is_current_user_admin"() from public;
grant execute on function public."is_current_user_admin"() to authenticated;
grant execute on function public."is_current_user_admin"() to service_role;
revoke execute on function public."is_guard_role"() from public;
grant execute on function public."is_guard_role"() to authenticated;
grant execute on function public."is_guard_role"() to service_role;
revoke execute on function public."is_platform_admin_role"() from public;
grant execute on function public."is_platform_admin_role"() to authenticated;
grant execute on function public."is_platform_admin_role"() to service_role;
revoke execute on function public."is_superadmin_role"() from public;
grant execute on function public."is_superadmin_role"() to authenticated;
grant execute on function public."is_superadmin_role"() to service_role;
revoke execute on function public."is_unit_occupant"(target_unit_id uuid) from public;
grant execute on function public."is_unit_occupant"(target_unit_id uuid) to authenticated;
grant execute on function public."is_unit_occupant"(target_unit_id uuid) to service_role;
revoke execute on function public."list_active_service_providers"(p_service_type text) from public;
grant execute on function public."list_active_service_providers"(p_service_type text) to authenticated;
grant execute on function public."list_active_service_providers"(p_service_type text) to service_role;
revoke execute on function public."log_activity"(p_action character varying, p_action_type character varying, p_resource character varying, p_resource_id character varying, p_details text, p_status character varying, p_severity character varying, p_metadata jsonb, p_ip_address inet, p_user_agent text, p_location character varying) from public;
grant execute on function public."log_activity"(p_action character varying, p_action_type character varying, p_resource character varying, p_resource_id character varying, p_details text, p_status character varying, p_severity character varying, p_metadata jsonb, p_ip_address inet, p_user_agent text, p_location character varying) to authenticated;
grant execute on function public."log_activity"(p_action character varying, p_action_type character varying, p_resource character varying, p_resource_id character varying, p_details text, p_status character varying, p_severity character varying, p_metadata jsonb, p_ip_address inet, p_user_agent text, p_location character varying) to service_role;
revoke execute on function public."mark_message_read"(message_id uuid) from public;
grant execute on function public."mark_message_read"(message_id uuid) to authenticated;
grant execute on function public."mark_message_read"(message_id uuid) to service_role;
revoke execute on function public."marketplace_vendor_followers_sync_trigger"() from public;
grant execute on function public."marketplace_vendor_followers_sync_trigger"() to authenticated;
grant execute on function public."marketplace_vendor_followers_sync_trigger"() to service_role;
revoke execute on function public."matches_current_actor"(target_id uuid) from public;
grant execute on function public."matches_current_actor"(target_id uuid) to authenticated;
grant execute on function public."matches_current_actor"(target_id uuid) to service_role;
revoke execute on function public."notify_users_on_notice_creation"() from public;
grant execute on function public."notify_users_on_notice_creation"() to authenticated;
grant execute on function public."notify_users_on_notice_creation"() to service_role;
revoke execute on function public."p27_read_vault_secret"(secret_name text) from public;
grant execute on function public."p27_read_vault_secret"(secret_name text) to authenticated;
grant execute on function public."p27_read_vault_secret"(secret_name text) to service_role;
revoke execute on function public."p27_read_vault_secret_by_id"(secret_id uuid) from public;
grant execute on function public."p27_read_vault_secret_by_id"(secret_id uuid) to authenticated;
grant execute on function public."p27_read_vault_secret_by_id"(secret_id uuid) to service_role;
revoke execute on function public."p27_upsert_vault_secret"(secret_name text, secret_value text, secret_description text) from public;
grant execute on function public."p27_upsert_vault_secret"(secret_name text, secret_value text, secret_description text) to authenticated;
grant execute on function public."p27_upsert_vault_secret"(secret_name text, secret_value text, secret_description text) to service_role;
revoke execute on function public."refresh_guard_assignment_scope"(target_guard_id uuid) from public;
grant execute on function public."refresh_guard_assignment_scope"(target_guard_id uuid) to authenticated;
grant execute on function public."refresh_guard_assignment_scope"(target_guard_id uuid) to service_role;
revoke execute on function public."send_join_request_approval_notification"() from public;
grant execute on function public."send_join_request_approval_notification"() to authenticated;
grant execute on function public."send_join_request_approval_notification"() to service_role;
revoke execute on function public."sync_amenity_booking_contract_fields"() from public;
grant execute on function public."sync_amenity_booking_contract_fields"() to authenticated;
grant execute on function public."sync_amenity_booking_contract_fields"() to service_role;
revoke execute on function public."sync_guard_profile_from_user"() from public;
grant execute on function public."sync_guard_profile_from_user"() to authenticated;
grant execute on function public."sync_guard_profile_from_user"() to service_role;
revoke execute on function public."sync_marketplace_vendor_follower_count"(target_vendor_id uuid) from public;
grant execute on function public."sync_marketplace_vendor_follower_count"(target_vendor_id uuid) to authenticated;
grant execute on function public."sync_marketplace_vendor_follower_count"(target_vendor_id uuid) to service_role;
revoke execute on function public."visitor_passes_set_community_id_from_unit"() from public;
grant execute on function public."visitor_passes_set_community_id_from_unit"() to authenticated;
grant execute on function public."visitor_passes_set_community_id_from_unit"() to service_role;

