begin;

create table if not exists public._backup_phase18_maintenance_unit_fix (
  backup_id bigint generated by default as identity primary key,
  maintenance_id bigint not null,
  previous_unit_id uuid not null,
  previous_updated_at timestamptz null,
  requester_profile_id uuid not null,
  backup_reason text not null default 'legacy requested_by/unit mismatch cleanup',
  backed_up_at timestamptz not null default now()
);

insert into public._backup_phase18_maintenance_unit_fix (
  maintenance_id,
  previous_unit_id,
  previous_updated_at,
  requester_profile_id,
  backup_reason
)
select
  mr.id,
  mr.unit_id,
  mr.updated_at,
  mr.requested_by,
  'aligned pending maintenance rows to requester profile unit'
from public.maintenance_requests mr
join public.profiles p
  on p.id = mr.requested_by
where lower(p.email) = 'thebornless144@gmail.com'
  and p.unit_id is not null
  and mr.unit_id <> p.unit_id
  and mr.status = 'pending'
  and not exists (
    select 1
    from public._backup_phase18_maintenance_unit_fix b
    where b.maintenance_id = mr.id
      and b.previous_unit_id = mr.unit_id
  );

update public.maintenance_requests mr
set
  unit_id = p.unit_id,
  updated_at = now()
from public.profiles p
where p.id = mr.requested_by
  and lower(p.email) = 'thebornless144@gmail.com'
  and p.unit_id is not null
  and mr.unit_id <> p.unit_id
  and mr.status = 'pending';

commit;

-- rollback helper (manual):
-- update public.maintenance_requests mr
-- set
--   unit_id = b.previous_unit_id,
--   updated_at = coalesce(b.previous_updated_at, mr.updated_at)
-- from (
--   select distinct on (maintenance_id)
--     maintenance_id,
--     previous_unit_id,
--     previous_updated_at
--   from public._backup_phase18_maintenance_unit_fix
--   order by maintenance_id, backed_up_at desc
-- ) b
-- where mr.id = b.maintenance_id;
