// Re-export from centralized image loader
import { propertyImages } from '@/utils/imageLoader';

export const properties = {
  'properties.property1.src': propertyImages.p1,
  'properties.property2.src': propertyImages.p2,
  'properties.property3.src': propertyImages.p3,
  'properties.property4.src': propertyImages.p4,
  'properties.property5.src': propertyImages.p5,
  'properties.property6.src': propertyImages.p6,
  'properties.property7.src': propertyImages.p7,
  'properties.property8.src': propertyImages.p8,
  'properties.property9.src': propertyImages.p9,
  'properties.property10.src': propertyImages.p10,
  'properties.property11.src': propertyImages.p11,
  'properties.property12.src': propertyImages.p12,
  'properties.property13.src': propertyImages.p13,
  'properties.property14.src': propertyImages.p14,
  'properties.property15.src': propertyImages.p15,
  'properties.property16.src': propertyImages.p16,
  property1: propertyImages.p1,
  property2: propertyImages.p2,
  property3: propertyImages.p3,
  property4: propertyImages.p4,
  property5: propertyImages.p5,
  property6: propertyImages.p6,
  property7: propertyImages.p7,
  property8: propertyImages.p8,
  property9: propertyImages.p9,
  property10: propertyImages.p10,
  property11: propertyImages.p11,
  property12: propertyImages.p12,
  property13: propertyImages.p13,
  property14: propertyImages.p14,
  property15: propertyImages.p15,
  property16: propertyImages.p16,
};

export const {
  property1,
  property2,
  property3,
  property4,
  property5,
  property6,
  property7,
  property8,
  property9,
  property10,
  property11,
  property12,
  property13,
  property14,
  property15,
  property16,
} = {
  property1: propertyImages.p1,
  property2: propertyImages.p2,
  property3: propertyImages.p3,
  property4: propertyImages.p4,
  property5: propertyImages.p5,
  property6: propertyImages.p6,
  property7: propertyImages.p7,
  property8: propertyImages.p8,
  property9: propertyImages.p9,
  property10: propertyImages.p10,
  property11: propertyImages.p11,
  property12: propertyImages.p12,
  property13: propertyImages.p13,
  property14: propertyImages.p14,
  property15: propertyImages.p15,
  property16: propertyImages.p16,
};
