-- Restore agency documents with complete sample data
INSERT INTO public.agency_documents (
  id,
  agency_id,
  name,
  category,
  type,
  description,
  file_url,
  file_size,
  file_type,
  uploaded_by,
  upload_date,
  last_modified,
  expiry_date,
  access,
  retention,
  status,
  version,
  tags,
  reminder_days,
  is_confidential,
  requires_approval,
  auto_archive,
  downloads,
  views
)
VALUES
  -- Original document 1
  (
    'doc1',
    'agency-001',
    'Agency License Certificate',
    'Legal Documents',
    'Certificate',
    'Official real estate agency license',
    '/docs/agency-license.pdf',
    2.5,
    'application/pdf',
    'Admin User',
    '2024-01-15',
    '2024-01-15',
    '2025-01-15',
    'Public',
    '7 Years',
    'Active',
    '1.0',
    ARRAY['license', 'legal', 'certificate'],
    30,
    false,
    true,
    false,
    15,
    45
  ),
  -- Original document 2
  (
    'doc2', 
    'agency-001',
    'Property Management Agreement Template',
    'Templates',
    'Agreement',
    'Standard template for property management agreements',
    '/docs/pm-agreement-template.docx',
    1.2,
    'application/docx',
    'Legal Team',
    '2024-02-10',
    '2024-02-10',
    null,
    'Internal',
    '5 Years',
    'Active',
    '2.1',
    ARRAY['template', 'agreement', 'property-management'],
    0,
    true,
    true,
    false,
    28,
    92
  ),
  -- Additional documents to restore
  (
    'doc3',
    'agency-001',
    'Employee Handbook 2024',
    'Policies',
    'Policy Document',
    'Comprehensive guide for agency employees',
    '/docs/employee-handbook-2024.pdf',
    3.8,
    'application/pdf',
    'HR Team',
    '2024-01-20',
    '2024-01-20',
    '2025-01-20',
    'Internal',
    '3 Years',
    'Active',
    '1.2',
    ARRAY['policy', 'hr', 'handbook'],
    0,
    true,
    false,
    true,
    45,
    120
  ),
  (
    'doc4',
    'agency-001',
    'Annual Compliance Report 2023',
    'Compliance',
    'Compliance Report',
    'Yearly compliance and regulatory report',
    '/docs/compliance-2023.pdf',
    5.2,
    'application/pdf',
    'Compliance Officer',
    '2024-01-30',
    '2024-01-30',
    '2025-01-30',
    'Restricted',
    'Permanent',
    'Active',
    '1.0',
    ARRAY['compliance', 'report', 'annual'],
    0,
    true,
    true,
    false,
    12,
    35
  ),
  (
    'doc5',
    'agency-001',
    'Client Onboarding Process',
    'Procedures',
    'SOP',
    'Standard operating procedure for new client onboarding',
    '/docs/client-onboarding-sop.pdf',
    1.8,
    'application/pdf',
    'Operations Team',
    '2024-02-15',
    '2024-02-15',
    null,
    'Internal',
    '5 Years',
    'Active',
    '2.0',
    ARRAY['sop', 'onboarding', 'client'],
    0,
    false,
    true,
    false,
    60,
    180
  ),
  (
    'doc6',
    'agency-001',
    'Q4 2023 Financial Statement',
    'Financial Records',
    'Report',
    'Quarterly financial performance report',
    '/docs/q4-2023-financials.xlsx',
    0.95,
    'application/xlsx',
    'Finance Team',
    '2024-01-25',
    '2024-01-25',
    null,
    'Confidential',
    '7 Years',
    'Active',
    '1.0',
    ARRAY['financial', 'quarterly', 'report'],
    0,
    true,
    true,
    false,
    8,
    25
  ),
  (
    'doc7',
    'agency-001',
    'Vendor Service Agreement',
    'Contracts',
    'Contract',
    'Standard agreement for property maintenance vendors',
    '/docs/vendor-agreement.docx',
    1.1,
    'application/docx',
    'Legal Team',
    '2024-02-20',
    '2024-02-20',
    '2025-02-20',
    'Internal',
    '5 Years',
    'Active',
    '1.1',
    ARRAY['contract', 'vendor', 'service'],
    30,
    true,
    true,
    false,
    15,
    40
  ),
  (
    'doc8',
    'agency-001',
    'Marketing Strategy 2024',
    'Reports',
    'Report',
    'Annual marketing plan and strategy document',
    '/docs/marketing-strategy-2024.pptx',
    2.3,
    'application/pptx',
    'Marketing Team',
    '2024-01-10',
    '2024-01-10',
    null,
    'Internal',
    '3 Years',
    'Active',
    '1.0',
    ARRAY['marketing', 'strategy', 'plan'],
    0,
    true,
    false,
    false,
    25,
    75
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  type = EXCLUDED.type,
  description = EXCLUDED.description,
  file_url = EXCLUDED.file_url,
  file_size = EXCLUDED.file_size,
  file_type = EXCLUDED.file_type,
  uploaded_by = EXCLUDED.uploaded_by,
  upload_date = EXCLUDED.upload_date,
  last_modified = EXCLUDED.last_modified,
  expiry_date = EXCLUDED.expiry_date,
  access = EXCLUDED.access,
  retention = EXCLUDED.retention,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  tags = EXCLUDED.tags,
  reminder_days = EXCLUDED.reminder_days,
  is_confidential = EXCLUDED.is_confidential,
  requires_approval = EXCLUDED.requires_approval,
  auto_archive = EXCLUDED.auto_archive,
  downloads = EXCLUDED.downloads,
  views = EXCLUDED.views; 